dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libssh2-1-dev
script:
  # Run your build commands next
  - g++ main.cpp -o main.out -lssh2 -std=c++11